// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihuncifdkmlcjuzjzalt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlodW5jaWZka21sY2p1emp6YWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTkyNjMsImV4cCI6MjA3MTkzNTI2M30.2PW0UlILGhFTZHZFNgXQZnz-PzMnEuHnuUhRpmM12dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});